import { Member } from "@src/types";

export const members: Member[] = [
  {
    id: "corporate",
    name: "Lisa Technologies",
    role: "Official",
    bio:
      "フードデリバリーを最適化する「フードデリバリーマネージャー（FDM）」を開発しています",
    avatarSrc: "/avatars/lisa_tech.png",
    sources: ["https://zenn.dev/lisatech/feed"],
    includeUrlRegex: "medium.com|zenn.dev",
    websiteUrl: "https://lisatech.jp/",
  },
  {
    id: "shintaronakagawa",
    name: "Shintaro Nakagawa",
    role: "Lead Engineer",
    bio:
      "学生時代よりソフトウェア開発・マーケティング業務に携わる。工学部卒（卒論AR実装)、農林水産省認定の６次産業での立ち上げ、D2Cブランドの立ち上げ、EC系SaaSの自社開発、フリーランスを経て、 Lisa Technologies(株)にジョイン",
    avatarSrc: "/avatars/catnose.jpg",
    sources: ["https://zenn.dev/sintaro/feed"],
    includeUrlRegex: "medium.com|zenn.dev",
    twitterUsername: "sintaro0221",
    githubUsername: "sintaro",
  },
  {
    id: "akarikusumoto",
    name: "Akari Kusumoto",
    role: "Backend dev",
    bio: "",
    avatarSrc: "/avatars/catnose.jpg",
    sources: [],
    includeUrlRegex: "medium.com|zenn.dev",
    twitterUsername: "",
    githubUsername: "AkariKusumoto",
    websiteUrl: "",
  },
  {
    id: "yutakamiyazaki",
    name: "Yutaka Miyazaki",
    role: "Frontend dev",
    bio:
      "フロントエンドエンジニア2年目の業務委託。前職はクラウドERPのカスタマイズ開発をしていました。",
    avatarSrc: "/avatars/yutaka_miyazaki.svg",
    sources: ["https://yutaaaaa.vercel.app/rss/feed.xml"],
    includeUrlRegex: "medium.com|zenn.dev",
    twitterUsername: "yutaaaaa___",
    githubUsername: "Yuta07",
    websiteUrl: "https://yutaaaaa.vercel.app/",
  },
  {
    id: "shotashimotani",
    name: "Shota Shimotani",
    role: "Designer",
    bio:
      "新卒で世田谷区の病院に理学療法士として勤務。1年で退職しプログラミング/Webデザインを学習。個人でLP, HPデザインを請け負い、2021年3月にLisa technologies (株)へjoin。現在はLisa technologis (株)と一部上場企業保険会社でUIデザインを担当しながら、個人でもデザイン制作を受けています。",
    avatarSrc: "/avatars/hajime_nakagawa.jpg",
    sources: [],
    includeUrlRegex: "zenn.dev",
    twitterUsername: "702_Creative",
    websiteUrl:
      "https://hexagonal-kingfisher-a2a.notion.site/portfolio-dfcdaa107e7b4aae80aa75b1aafd398e",
  },
  {
    id: "hajimenakagawa",
    name: "Hajime Nakagawa",
    role: "Intern",
    bio: "当ブログの立ち上げ担当",
    avatarSrc: "/avatars/hajime_nakagawa.jpg",
    sources: ["https://zenn.dev/ikenohi/feed"],
    includeUrlRegex: "zenn.dev",
    twitterUsername: "hajixxnaka",
    githubUsername: "HajimexxxNakagawa",
    websiteUrl:
      "https://www.notion.so/hjmnkgw/ff0979cf63834144935c6e83bbec9916",
  },
  {
    id: "gomatsuda",
    name: "Go Matsuda",
    role: "Intern",
    bio: "",
    avatarSrc: "/avatars/hajime_nakagawa.jpg",
    sources: [],
    includeUrlRegex: "zenn.dev",
    twitterUsername: "",
    githubUsername: "",
    websiteUrl: "",
  },
];
