import { Member } from "@src/types";

export const members: Member[] = [
  {
    id: "saqoosha",
    name: "Saqoosha",
    role: "CTO, Programmer",
    bio: "",
    avatarSrc: "/avatars/saqoosha.jpg",
    sources: ["https://qiita-feed.saqoosha.workers.dev/saqoosha",],
    twitterUsername: "Saqoosha",
    githubUsername: "saqoosha",
    websiteUrl: "https://saqoo.sh/a",
  },
  {
    id: "hige",
    name: "Takanobu Izukawa",
    role: "System Engineer",
    bio: "",
    avatarSrc: "/avatars/hige.jpg",
    sources: ["https://zenn.dev/hige/feed?include_scraps=1", "https://qiita-feed.saqoosha.workers.dev/soundkitchen"],
    twitterUsername: "soundkitchen",
    githubUsername: "soundkitchen",
    websiteUrl: "http://izukawa.org/",
  },
  {
    id: "asus4",
    name: "Koki Ibukuro",
    role: "Artist",
    bio: "",
    avatarSrc: "/avatars/asus4.jpg",
    sources: ["https://zenn.dev/asus4/feed?include_scraps=1", "https://qiita-feed.saqoosha.workers.dev/asus4"],
    twitterUsername: "asus4",
    githubUsername: "asus4",
    websiteUrl: "https://www.koki-ibukuro.com/",
  },
  {
    id: "wtshm",
    name: "Kenta Watashima",
    role: "Programmer",
    bio: "",
    avatarSrc: "/avatars/wtshm.jpg",
    sources: ["https://zenn.dev/wtshm/feed?include_scraps=1", "https://qiita-feed.saqoosha.workers.dev/wtshm"],
    twitterUsername: "wtshm",
    githubUsername: "wtshm",
    websiteUrl: "https://achr.me/",
  },
  {
    id: "kidapu",
    name: "Tatsuya Kida",
    role: "Engineer, Programmer",
    bio: "",
    avatarSrc: "/avatars/kidapu.jpg",
    sources: ["https://qiita-feed.saqoosha.workers.dev/kidapu", "https://note.com/kidapu/rss", "https://zenn.dev/kidapu/feed?include_scraps=1"],
    twitterUsername: "kidapu",
    githubUsername: "kidapu",
  },
  {
    id: "murasaqi",
    name: "murasaqi",
    role: "Visual Artist, Programmer",
    avatarSrc: "/avatars/murasaqi.jpg",
    sources: ["https://qiita-feed.saqoosha.workers.dev/Murasaqi", "https://zenn.dev/murasaqi/feed?include_scraps=1"],
    twitterUsername: "murasaki_0606",
    githubUsername: "murasaqi",
  },
  {
    id: "migifun",
    name: "Takashi Okada",
    role: "Engineer",
    avatarSrc: "/avatars/migifun.jpg",
    sources: ["https://note.com/migifun/rss", "https://qiita.com/migifun/feed"],
    twitterUsername: "migifun",
    githubUsername: "migifun",
  },
  {
    id: "genkitoyama",
    name: "Genki Toyama",
    role: "Engineer",
    bio: "",
    avatarSrc: "/avatars/genkitoyama.jpg",
    sources: ["https://qiita-feed.saqoosha.workers.dev/genkitoyama"],
    githubUsername: "genkitoyama",
    twitterUsername: "genkitoyama",
  },
  {
    id: "ok",
    name: "Kazuto Omori",
    role: "Engineer, Programmer",
    avatarSrc: "/avatars/ok.jpg",
    sources: ["https://note.com/ooo_ubi_ooo/rss"],
    githubUsername: "ubiquitous-o",
    twitterUsername: "ooo_ubi_ooo",
  },
];
