name: deploy website
on:
  # 画面から手動実行
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: 'master'
        required: true
  # 定期実行
  schedule:
    - cron:  '0 2 * * *'
  # プルリクごとに実行
  pull_request_target:
  # masterマージ時に実行
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Recreate all posts
        shell: bash
        run: |
          npm install
          npm run build:posts
      - uses: amondnet/vercel-action@v20
      - uses: ./
        id: now-deployment-staging
        if: github.event_name == 'pull_request_target'
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.TEAM_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          scope: hitto
          working-directory: ./
      - uses: ./
        id: now-deployment-production
        if: github.event_name == 'push'
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.TEAM_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          scope: hitto
          vercel-args: '--prod'
          working-directory: ./